// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating standardized music sheet filenames based on extracted metadata.
 *
 * - generateMusicSheetFilename - A function that takes music sheet metadata as input and returns a standardized filename.
 * - MusicSheetMetadataInput - The input type for the generateMusicSheetFilename function.
 * - MusicSheetFilenameOutput - The return type for the generateMusicSheetFilename function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MusicSheetMetadataInputSchema = z.object({
  compositionType: z.string().describe('The type of composition or arrangement (e.g., percussion ensemble, saxophone ensemble).'),
  compositionName: z.string().describe('The name of the composition.'),
  composer: z.string().describe('The composer of the music sheet.'),
  arranger: z.string().optional().describe('The arranger of the music sheet, if applicable.'),
});
export type MusicSheetMetadataInput = z.infer<typeof MusicSheetMetadataInputSchema>;

const MusicSheetFilenameOutputSchema = z.object({
  filename: z.string().describe('The generated standardized filename for the music sheet.'),
});
export type MusicSheetFilenameOutput = z.infer<typeof MusicSheetFilenameOutputSchema>;

export async function generateMusicSheetFilename(input: MusicSheetMetadataInput): Promise<MusicSheetFilenameOutput> {
  return generateMusicSheetFilenameFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMusicSheetFilenamePrompt',
  input: {schema: MusicSheetMetadataInputSchema},
  output: {schema: MusicSheetFilenameOutputSchema},
  prompt: `You are a music librarian who is tasked with generating a standardized filename for a music sheet.

  Here is the metadata for the music sheet:
  Type of Composition/Arrangement: {{{compositionType}}}
  Composition Name: {{{compositionName}}}
  Composer: {{{composer}}}
  Arranger: {{#if arranger}}{{{arranger}}}{{else}}Arranged by: {{{composer}}}{{/if}}

  Generate a filename that follows this format:
  [Type of Composition or Arrangement] - [Composition Name] - [Composer and Arranger].pdf

  If there is no arranger, then the filename will follow this format:
  [Type of Composition or Arrangement] - [Composition Name] - [Composer].pdf

  Ensure the filename is suitable for use in Google Drive and does not contain any invalid characters.
  Return ONLY the filename in the output. Do not include any additional text or explanations.
  `,
});

const generateMusicSheetFilenameFlow = ai.defineFlow(
  {
    name: 'generateMusicSheetFilenameFlow',
    inputSchema: MusicSheetMetadataInputSchema,
    outputSchema: MusicSheetFilenameOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
