// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating standardized music sheet filenames based on extracted metadata.
 *
 * - generateMusicSheetFilename - A function that takes music sheet metadata as input and returns a standardized filename.
 * - MusicSheetMetadataInput - The input type for the generateMusicSheetFilename function.
 * - MusicSheetFilenameOutput - The return type for the generateMusicSheetFilename function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const MusicSheetMetadataInputSchema = z.object({
  fileSubject: z.string().describe('The specific part or content of the file (e.g., "Full Score", "Violin I").'),
  instrumentations: z.string().describe('A comma-separated list of instruments or voice parts (e.g., "Flute, Oboe", "Piano"). This will be used to form part of the filename.'),
});
export type MusicSheetMetadataInput = z.infer<typeof MusicSheetMetadataInputSchema>;

const MusicSheetFilenameOutputSchema = z.object({
  filename: z.string().describe('The generated standardized filename for the music sheet.'),
});
export type MusicSheetFilenameOutput = z.infer<typeof MusicSheetFilenameOutputSchema>;

export async function generateMusicSheetFilename(input: MusicSheetMetadataInput): Promise<MusicSheetFilenameOutput> {
  return generateMusicSheetFilenameFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateMusicSheetFilenamePrompt',
  input: {schema: MusicSheetMetadataInputSchema},
  output: {schema: MusicSheetFilenameOutputSchema},
  prompt: `You are a music librarian tasked with generating a standardized filename.

  Metadata:
  - File Subject: {{{fileSubject}}}
  - Instrumentations (comma-separated): {{{instrumentations}}}

  Generate a filename using this format:
  [File Subject] - [Instrumentations joined by hyphens].pdf

  For example, if File Subject is "Violin I" and Instrumentations is "Violin, Viola, Cello", the filename should be:
  "Violin I - Violin-Viola-Cello.pdf"

  If File Subject is "Adagio" and Instrumentations is "Flute", the filename should be:
  "Adagio - Flute.pdf"

  If File Subject is "Full Score" and Instrumentations is "Full Score", the filename should be:
  "Full Score - Full Score.pdf"

  Ensure the filename is suitable for use in Google Drive and does not contain any invalid characters.
  Replace any slashes or other invalid characters in the File Subject or Instrumentations with hyphens before constructing the filename.
  Return ONLY the filename in the output. Do not include any additional text or explanations.
  `,
});

const generateMusicSheetFilenameFlow = ai.defineFlow(
  {
    name: 'generateMusicSheetFilenameFlow',
    inputSchema: MusicSheetMetadataInputSchema,
    outputSchema: MusicSheetFilenameOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
